service: serverless-data-pipeline

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1

custom:
  bucket: ${self:service}-<add-a-unique-string-here>

functions:
  unzip:
    handler: lambda/unzip.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/
            - suffix: .zip
    environment:
        DEST_BUCKET: ${self:custom.bucket}
        DEST_KEY: unzip/
        JOB_NAME: unzip

resources:
  Resources:
    GlueJob:
      Type: AWS::Glue::Job
      Properties: 
        Role: arn:aws:iam::077590795309:role/serverless-data-pipeline-glue
        Command:   
          Name: pythonshell  
          ScriptLocation: s3://aws-glue-target-serverless-data-pipeline/unzip.py
        Name: unzip
    
    S3GlueScripts:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-glue-target-serverless-data-pipeline
